### ISSUE TITLE
z-indexが汚すぎる

### ISSUE THREAD

**Issue by NMMN** [happou31/nico_downloader#1]
CSSのz-indexが汚すぎます。
きれいなものをさがしにいくべきでは？

該当箇所：/css/style.css (7)
`z-index: 1919810;`

**Comment by hapo31** [comment]
issueの指摘ありがとうございます。  
該当行ですが、メインスクリプトからは一切参照されていないため、汚染の心配はございません。    
元となったテンプレートをコピペして本拡張は作られているため、消し忘れがあったようです。

**Comment by hapo31** [comment]
当該cssファイルは削除することで対応とさせて頂き、本issueはcloseします。
